// Generado por tool/sync_catalogs.dart desde shared/modes.json y shared/plans.json.
// No editar a mano: cambia los JSON y vuelve a correr el comando.

/// Contenido de shared/modes.json.
const modesJson = r'''
{
  "$comment": "Modos de negocio de VOXON. La app y las Cloud Functions leen este archivo. Un modo enciende módulos, trae categorías de ejemplo y fija reglas fiscales; no es código aparte.",
  "modules": {
    "catalog": "Catálogo de productos y precios",
    "barcode": "Lector de código de barras",
    "scale": "Venta por peso con balanza",
    "fractions": "Venta en fracciones y al detalle",
    "credit": "Fiao con límite y abonos",
    "delivery": "Delivery y pedidos para llevar",
    "promotions": "Ofertas, combos y precios por cantidad",
    "multiRegister": "Varias cajas a la vez con cuadre por caja",
    "receiving": "Recepción de mercancía y compras",
    "tables": "Mapa de mesas y áreas",
    "orders": "Comandas por mesa, para llevar o delivery",
    "kitchen": "Pantalla de cocina y bar por estación",
    "modifiers": "Modificadores y notas por plato",
    "splitBill": "Dividir y unir cuentas",
    "legalTip": "Propina legal del 10 %",
    "reservations": "Reservaciones",
    "variants": "Tallas, colores y variantes",
    "serials": "Números de serie e IMEI",
    "warranty": "Garantías",
    "layaway": "Separados y abonos",
    "expiry": "Lotes y fechas de vencimiento",
    "prescriptions": "Control de recetas",
    "appointments": "Citas y agenda",
    "services": "Servicios por tiempo o por empleado",
    "commissions": "Comisiones por empleado",
    "workOrders": "Órdenes de trabajo con estado",
    "measures": "Venta por medida (metro, pie, galón)",
    "happyHour": "Precios por horario"
  },
  "modes": [
    {
      "id": "supermarket",
      "order": 1,
      "status": "priority",
      "name": "Supermercado",
      "description": "Cajas rápidas con lector de código, balanza y ofertas",
      "icon": "local_grocery_store",
      "color": "#2E7D32",
      "priceMode": "tax_included",
      "legalTip": false,
      "modules": ["catalog", "barcode", "scale", "promotions", "multiRegister", "receiving", "credit"],
      "categories": ["Víveres", "Carnes", "Lácteos y huevos", "Frutas y vegetales", "Bebidas", "Limpieza", "Cuidado personal", "Panadería", "Congelados"]
    },
    {
      "id": "colmado",
      "order": 2,
      "status": "priority",
      "name": "Colmado o minimercado",
      "description": "Botones grandes, fracciones, fiao y delivery del barrio",
      "icon": "storefront",
      "color": "#EF6C00",
      "priceMode": "tax_included",
      "legalTip": false,
      "modules": ["catalog", "barcode", "fractions", "credit", "delivery", "promotions"],
      "categories": ["Víveres", "Bebidas", "Cervezas y romos", "Cigarrillos", "Picaderas", "Limpieza", "Recargas"]
    },
    {
      "id": "restaurant",
      "order": 3,
      "status": "priority",
      "name": "Restaurante",
      "description": "Mesas, comandas, cocina y propina legal",
      "icon": "restaurant",
      "color": "#C62828",
      "priceMode": "tax_excluded",
      "legalTip": true,
      "modules": ["catalog", "tables", "orders", "kitchen", "modifiers", "splitBill", "legalTip", "delivery", "reservations"],
      "stations": ["Cocina", "Bar"],
      "categories": ["Entradas", "Platos fuertes", "Acompañantes", "Postres", "Bebidas", "Tragos"]
    },
    {
      "id": "store",
      "order": 4,
      "status": "priority",
      "name": "Tienda",
      "description": "Tecnología, variedades o artículos: variantes, series y garantías",
      "icon": "shopping_bag",
      "color": "#1565C0",
      "priceMode": "tax_included",
      "legalTip": false,
      "modules": ["catalog", "barcode", "variants", "serials", "warranty", "layaway", "promotions"],
      "categories": ["Accesorios", "Electrónica", "Hogar", "Juguetes", "Regalos"]
    },
    {
      "id": "bar",
      "order": 5,
      "status": "planned",
      "name": "Bar o discoteca",
      "description": "Barras, mesas, cuentas abiertas y precios por horario",
      "icon": "local_bar",
      "color": "#6A1B9A",
      "priceMode": "tax_excluded",
      "legalTip": true,
      "modules": ["catalog", "tables", "orders", "kitchen", "splitBill", "legalTip", "happyHour"],
      "stations": ["Barra"],
      "categories": ["Cervezas", "Romos", "Whisky", "Cocteles", "Sin alcohol", "Picaderas"]
    },
    {
      "id": "cafe",
      "order": 6,
      "status": "planned",
      "name": "Cafetería o panadería",
      "description": "Venta rápida en mostrador, pedidos y modificadores",
      "icon": "local_cafe",
      "color": "#6D4C41",
      "priceMode": "tax_included",
      "legalTip": false,
      "modules": ["catalog", "orders", "modifiers", "kitchen", "delivery", "promotions"],
      "stations": ["Barra"],
      "categories": ["Café", "Bebidas frías", "Panes", "Dulces", "Desayunos", "Sándwiches"]
    },
    {
      "id": "fastfood",
      "order": 7,
      "status": "planned",
      "name": "Comida rápida o food truck",
      "description": "Pedido en mostrador con número y pantalla de cocina",
      "icon": "fastfood",
      "color": "#F9A825",
      "priceMode": "tax_included",
      "legalTip": false,
      "modules": ["catalog", "orders", "kitchen", "modifiers", "delivery", "promotions"],
      "stations": ["Cocina"],
      "categories": ["Combos", "Hamburguesas", "Pica pollo", "Acompañantes", "Bebidas", "Postres"]
    },
    {
      "id": "pharmacy",
      "order": 8,
      "status": "planned",
      "name": "Farmacia",
      "description": "Lotes, vencimientos y control de recetas",
      "icon": "local_pharmacy",
      "color": "#00897B",
      "priceMode": "tax_included",
      "legalTip": false,
      "modules": ["catalog", "barcode", "expiry", "prescriptions", "credit", "delivery"],
      "categories": ["Medicamentos", "Vitaminas", "Cuidado personal", "Bebés", "Primeros auxilios"]
    },
    {
      "id": "hardware",
      "order": 9,
      "status": "planned",
      "name": "Ferretería",
      "description": "Venta por medida, cotizaciones y crédito a clientes",
      "icon": "hardware",
      "color": "#5D4037",
      "priceMode": "tax_included",
      "legalTip": false,
      "modules": ["catalog", "barcode", "measures", "credit", "receiving", "delivery"],
      "categories": ["Herramientas", "Plomería", "Electricidad", "Pinturas", "Construcción", "Tornillería"]
    },
    {
      "id": "clothing",
      "order": 10,
      "status": "planned",
      "name": "Ropa y boutique",
      "description": "Tallas, colores, separados y cambios",
      "icon": "checkroom",
      "color": "#AD1457",
      "priceMode": "tax_included",
      "legalTip": false,
      "modules": ["catalog", "barcode", "variants", "layaway", "promotions"],
      "categories": ["Damas", "Caballeros", "Niños", "Accesorios", "Ropa interior"]
    },
    {
      "id": "shoes",
      "order": 11,
      "status": "planned",
      "name": "Zapatería",
      "description": "Numeraciones por modelo, separados y cambios",
      "icon": "ice_skating",
      "color": "#4E342E",
      "priceMode": "tax_included",
      "legalTip": false,
      "modules": ["catalog", "barcode", "variants", "layaway", "promotions"],
      "categories": ["Damas", "Caballeros", "Niños", "Deportivos", "Accesorios"]
    },
    {
      "id": "electronics",
      "order": 12,
      "status": "planned",
      "name": "Celulares y electrónica",
      "description": "IMEI, garantías, reparaciones y financiamiento",
      "icon": "smartphone",
      "color": "#283593",
      "priceMode": "tax_included",
      "legalTip": false,
      "modules": ["catalog", "barcode", "serials", "warranty", "workOrders", "layaway"],
      "categories": ["Celulares", "Accesorios", "Audio", "Computadoras", "Reparaciones"]
    },
    {
      "id": "beauty",
      "order": 13,
      "status": "planned",
      "name": "Salón de belleza o barbería",
      "description": "Citas, servicios por empleado y comisiones",
      "icon": "content_cut",
      "color": "#D81B60",
      "priceMode": "tax_included",
      "legalTip": false,
      "modules": ["catalog", "appointments", "services", "commissions"],
      "categories": ["Cortes", "Color", "Uñas", "Tratamientos", "Productos"]
    },
    {
      "id": "liquor",
      "order": 14,
      "status": "planned",
      "name": "Licorería o drink",
      "description": "Lector de código, combos, fiao y delivery",
      "icon": "liquor",
      "color": "#8E24AA",
      "priceMode": "tax_included",
      "legalTip": false,
      "modules": ["catalog", "barcode", "promotions", "credit", "delivery"],
      "categories": ["Cervezas", "Romos", "Whisky", "Vinos", "Hielo y refrescos", "Picaderas"]
    },
    {
      "id": "butcher",
      "order": 15,
      "status": "planned",
      "name": "Carnicería o pescadería",
      "description": "Venta por peso con balanza y cortes por pedido",
      "icon": "set_meal",
      "color": "#B71C1C",
      "priceMode": "tax_included",
      "legalTip": false,
      "modules": ["catalog", "scale", "fractions", "orders", "credit", "delivery"],
      "categories": ["Res", "Cerdo", "Pollo", "Pescados y mariscos", "Embutidos"]
    },
    {
      "id": "produce",
      "order": 16,
      "status": "planned",
      "name": "Frutería y vegetales",
      "description": "Peso, fracciones y precios que cambian cada día",
      "icon": "eco",
      "color": "#558B2F",
      "priceMode": "tax_included",
      "legalTip": false,
      "modules": ["catalog", "scale", "fractions", "credit", "delivery"],
      "categories": ["Frutas", "Vegetales", "Víveres", "Hierbas", "Jugos"]
    },
    {
      "id": "stationery",
      "order": 17,
      "status": "planned",
      "name": "Librería y papelería",
      "description": "Temporada escolar, listas de útiles y fotocopias",
      "icon": "menu_book",
      "color": "#0277BD",
      "priceMode": "tax_included",
      "legalTip": false,
      "modules": ["catalog", "barcode", "services", "promotions", "layaway"],
      "categories": ["Útiles escolares", "Libros", "Oficina", "Impresión y copias", "Regalos"]
    },
    {
      "id": "autoparts",
      "order": 18,
      "status": "planned",
      "name": "Repuestos y autopartes",
      "description": "Búsqueda por marca y modelo, garantías y crédito",
      "icon": "car_repair",
      "color": "#37474F",
      "priceMode": "tax_included",
      "legalTip": false,
      "modules": ["catalog", "barcode", "warranty", "credit", "workOrders", "receiving"],
      "categories": ["Motor", "Frenos", "Suspensión", "Eléctrico", "Lubricantes", "Gomas"]
    },
    {
      "id": "icecream",
      "order": 19,
      "status": "planned",
      "name": "Heladería o repostería",
      "description": "Sabores, tamaños, pedidos por encargo y delivery",
      "icon": "icecream",
      "color": "#EC407A",
      "priceMode": "tax_included",
      "legalTip": false,
      "modules": ["catalog", "variants", "modifiers", "orders", "delivery", "promotions"],
      "categories": ["Helados", "Batidas", "Bizcochos", "Postres", "Encargos"]
    },
    {
      "id": "laundry",
      "order": 20,
      "status": "planned",
      "name": "Lavandería",
      "description": "Órdenes de ropa con estado, entrega y cobro al retirar",
      "icon": "local_laundry_service",
      "color": "#00838F",
      "priceMode": "tax_included",
      "legalTip": false,
      "modules": ["catalog", "services", "workOrders", "delivery", "credit"],
      "categories": ["Lavado", "Planchado", "Lavado en seco", "Edredones", "Especiales"]
    }
  ]
}
''';

/// Contenido de shared/plans.json.
const plansJson = r'''
{
  "$comment": "Única fuente de los planes: las apps (Dart) y las Cloud Functions (TypeScript) leen este archivo. Los precios son provisionales y se confirman antes de publicar en Stripe. Los modos de negocio están en modes.json.",
  "provisionalPrices": true,
  "currency": "USD",
  "trialDays": 14,
  "trialTier": "v90",
  "features": {
    "sales": "Vender, cobrar y ticket",
    "cash": "Apertura y cierre de caja con cuadre",
    "customers": "Clientes",
    "dayReport": "Resumen del día",
    "inventory": "Inventario con costo promedio y mínimos",
    "credit": "Fiao con límite y abonos",
    "restaurant": "Mesas, comandas y cocina",
    "purchases": "Compras a suplidores",
    "ncf": "Comprobantes fiscales (NCF) y formatos 606/607",
    "backups": "Respaldos y exportables",
    "posDevices": "Cajas con VOXON POS y la marca del negocio",
    "branches": "Varias sucursales con reportes juntos",
    "shifts": "Empleados por turno y control de acceso",
    "advancedReports": "Comparativos, márgenes y tendencias",
    "costs": "Costos y rentabilidad por producto",
    "api": "API para integrar otros sistemas",
    "multiCompany": "Varias empresas en una cuenta",
    "integrations": "Integraciones (delivery, contabilidad)",
    "priority": "Soporte prioritario"
  },
  "$limits": "0 significa sin tope. users cuenta administradores con cuenta y empleados con PIN; devices cuenta cajas con VOXON POS.",
  "tiers": {
    "v45": {
      "name": "VOXON 45",
      "tagline": "Vender desde un solo equipo",
      "priceMonthly": 9,
      "limits": { "instances": 1, "users": 2, "products": 300, "devices": 0 },
      "features": ["sales", "cash", "customers", "dayReport"]
    },
    "v90": {
      "name": "VOXON 90",
      "tagline": "El negocio completo",
      "priceMonthly": 19,
      "limits": { "instances": 2, "users": 8, "products": 5000, "devices": 3 },
      "features": [
        "sales",
        "cash",
        "customers",
        "dayReport",
        "inventory",
        "credit",
        "restaurant",
        "purchases",
        "ncf",
        "backups",
        "posDevices"
      ]
    },
    "v180": {
      "name": "VOXON 180",
      "tagline": "Varias sucursales",
      "priceMonthly": 39,
      "limits": { "instances": 5, "users": 30, "products": 50000, "devices": 10 },
      "features": [
        "sales",
        "cash",
        "customers",
        "dayReport",
        "inventory",
        "credit",
        "restaurant",
        "purchases",
        "ncf",
        "backups",
        "posDevices",
        "branches",
        "shifts",
        "advancedReports",
        "costs"
      ]
    },
    "v360": {
      "name": "VOXON 360",
      "tagline": "Cadena o empresa",
      "priceMonthly": 79,
      "limits": { "instances": 0, "users": 0, "products": 0, "devices": 0 },
      "features": [
        "sales",
        "cash",
        "customers",
        "dayReport",
        "inventory",
        "credit",
        "restaurant",
        "purchases",
        "ncf",
        "backups",
        "posDevices",
        "branches",
        "shifts",
        "advancedReports",
        "costs",
        "api",
        "multiCompany",
        "integrations",
        "priority"
      ]
    }
  }
}
''';
